// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAweN-cFPavPlK-nS0TNBRX7PEPqWpgCRo',
    appId: '1:441060738052:web:a0cf6893476ba09732a151',
    messagingSenderId: '441060738052',
    projectId: 'hubneredu',
    authDomain: 'hubneredu.firebaseapp.com',
    storageBucket: 'hubneredu.firebasestorage.app',
    measurementId: 'G-HSCQGSBQLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGcLi64sdami38IrRC-v7Q31599F4bDd4',
    appId: '1:441060738052:android:6ae1f06bb9f6836432a151',
    messagingSenderId: '441060738052',
    projectId: 'hubneredu',
    storageBucket: 'hubneredu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGcLi64sdami38IrRC-v7Q31599F4bDd4',
    appId: '1:441060738052:ios:cc00a1232f81f12d518a61',
    messagingSenderId: '441060738052',
    projectId: 'hubneredu',
    storageBucket: 'hubneredu.firebasestorage.app',
    iosBundleId: 'com.hubner.hubner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGcLi64sdami38IrRC-v7Q31599F4bDd4',
    appId: '1:441060738052:ios:cc00a1232f81f12d518a61',
    messagingSenderId: '441060738052',
    projectId: 'hubneredu',
    storageBucket: 'hubneredu.firebasestorage.app',
    iosBundleId: 'com.hubner.hubner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAweN-cFPavPlK-nS0TNBRX7PEPqWpgCRo',
    appId: '1:441060738052:web:a0cf6893476ba09732a151',
    messagingSenderId: '441060738052',
    projectId: 'hubneredu',
    authDomain: 'hubneredu.firebaseapp.com',
    storageBucket: 'hubneredu.firebasestorage.app',
    measurementId: 'G-HSCQGSBQLJ',
  );

}
